In [1]:
!pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/envs/bia/lib/python3.10/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /opt/anaconda3/envs/bia/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/bia/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/bia/lib/python3.10/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/bia/lib/python3.10/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/bia/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("./data_files/data.csv")

In [3]:
df.rename(columns={'Index':'auto_od'}

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Numeric_Column
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/,58
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/,62
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/,91
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/,41
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/,20
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/,64
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/,83
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/,10
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/,98

In [13]:
list(df.columns)

['Index',
 'Customer Id',
 'First Name',
 'Last Name',
 'Company',
 'City',
 'Country',
 'Phone 1',
 'Phone 2',
 'Email',
 'Subscription Date',
 'Website',
 'Numeric_Column']

In [21]:
df['Customer Id']

0     DD37Cf93aecA6Dc
1     1Ef7b82A4CAAD10
2     6F94879bDAfE5a6
3     5Cef8BFA16c5e3c
4     053d585Ab6b3159
           ...
95    cb8E23e48d22Eae
96    CeD220bdAaCfaDf
97    28CDbC0dFe4b1Db
98    c23d1D9EE8DEB0A
99    2354a0E336A91A1
Name: Customer Id, Length: 100, dtype: object

In [30]:
df[['Customer Id']]

        Customer Id
0   DD37Cf93aecA6Dc
1   1Ef7b82A4CAAD10
2   6F94879bDAfE5a6
3   5Cef8BFA16c5e3c
4   053d585Ab6b3159
..              ...
95  cb8E23e48d22Eae
96  CeD220bdAaCfaDf
97  28CDbC0dFe4b1Db
98  c23d1D9EE8DEB0A
99  2354a0E336A91A1

[100 rows x 1 columns]

In [34]:
df[['Customer Id','Website']]

        Customer Id                            Website
0   DD37Cf93aecA6Dc         http://www.stephenson.com/
1   1Ef7b82A4CAAD10              http://www.hobbs.com/
2   6F94879bDAfE5a6           http://www.lawrence.com/
3   5Cef8BFA16c5e3c         http://www.good-lyons.com/
4   053d585Ab6b3159        https://goodwin-ingram.com/
..              ...                                ...
95  cb8E23e48d22Eae            http://hayes-perez.com/
96  CeD220bdAaCfaDf         https://novak-allison.com/
97  28CDbC0dFe4b1Db              https://www.ross.com/
98  c23d1D9EE8DEB0A               http://watkins.info/
99  2354a0E336A91A1  http://www.hatfield-saunders.net/

[100 rows x 2 columns]

In [38]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Numeric_Column
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/,58
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/,62
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/,91
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/,41
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/,50

In [36]:
df.tail()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Numeric_Column
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/,20
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/,64
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/,83
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/,10
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/,98

In [40]:
df.describe()

            Index  Numeric_Column
count  100.000000      100.000000
mean    50.500000       52.510000
std     29.011492       26.881519
min      1.000000        1.000000
25%     25.750000       31.500000
50%     50.500000       52.500000
75%     75.250000       73.250000
max    100.000000       98.000000

In [41]:
df.dtypes

Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
Numeric_Column        int64
dtype: object

In [43]:
df['Index'] = df['Index'].astype(str)

0       1
1       2
2       3
3       4
4       5
     ...
95     96
96     97
97     98
98     99
99    100
Name: Index, Length: 100, dtype: object

In [50]:
lst_of_columns = list(df.columns)

In [53]:
for i in lst_of_columns:
    if i in ['Phone 1','Phone 2','Company']:
        df[i] = df[i].astype(str)

In [55]:
df.dtypes

Index                object
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
Numeric_Column       object
dtype: object

In [57]:
type(df.columns)

pandas.core.indexes.base.Index

In [59]:
df['Index'] = df['Index'].astype(float)

In [64]:
df['Subscription Date']=pd.to_datetime(df['Subscription Date'])

/var/folders/hv/v2yn6r8d6xx6zjxk3vfdpgdh0000gn/T/ipykernel_12510/3515405708.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Subscription Date']=pd.to_datetime(df['Subscription Date'])

In [65]:
df.dtypes

Index                       float64
Customer Id                  object
First Name                   object
Last Name                    object
Company                      object
City                         object
Country                      object
Phone 1                      object
Phone 2                      object
Email                        object
Subscription Date    datetime64[ns]
Website                      object
Numeric_Column               object
dtype: object

In [68]:
df['Index'] = df['Index'].astype(int)
df['Index2'] = df['Index'].astype(int)

In [70]:
abc = df[['Index','Index2']]

In [71]:
abc.corr()

        Index  Index2
Index     1.0     1.0
Index2    1.0     1.0

1. How to check null values in all columns
2. forward filling
3. backward filling
4. github and gitscm
5. use the excel file and convert all the graphs in python (matplotlib,plotly,seaborn)
6. what is inplace in pandas ?

In [73]:
df_students = pd.read_csv("students.csv")
df_professors = pd.read_csv("professors.csv")

In [80]:
def mul(fn,sn):
    return fn*sn

In [82]:
mul(fn=2,sn=3)

6

In [85]:
df_students = df_students.rename(columns={'id_number':'id','Name':'name'})

In [86]:
df_students

    id               name  Age Gender
0  204        James Smith   26      M
1  202    Maria Rodriguez   22      F
2  264        David Smith   24      M
3  136    Patricia Garcia   21      F
4  238  Jessica Hernandez   25      F

In [75]:
df_professors

         Prof_name  id_number Department
0     Thomas Smith        204        ECE
1  Margaret Garcia        264         EE
2    James Johnson        108        CSE
3   Richard Miller        238         ME
4   Margaret MOORE        136         CE

In [103]:
pd.merge(df_students,df_professors,left_on=['id'],right_on=['id_number'],how='right')

      id             name   Age Gender        Prof_name  id_number Department
0  204.0      James Smith  26.0      M     Thomas Smith        204        ECE
1  264.0      David Smith  24.0      M  Margaret Garcia        264         EE
2    NaN              NaN   NaN    NaN    James Johnson        108        CSE
3    NaN              NaN   NaN    NaN   Richard Miller        238         ME
4  136.0  Patricia Garcia  21.0      F   Margaret MOORE        136         CE

In [92]:
df_students['id'] = np.where(df_students['id']==238,500,df_students['id'])

In [93]:
df_students

    id               name  Age Gender
0  204        James Smith   26      M
1  202    Maria Rodriguez   22      F
2  264        David Smith   24      M
3  136    Patricia Garcia   21      F
4  500  Jessica Hernandez   25      F